# This workflow uploads codecov

name: Codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip >/dev/null
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - >/dev/null
        source $HOME/.poetry/env
        poetry lock --quiet --no-interaction
        poetry export --quiet --no-interaction --dev --without-hashes --format requirements.txt --output requirements.txt
        python -m pip install --requirement requirements.txt >/dev/null

    - name: Tests with coverage
      run: |
        pytest --cov

    - name: Upload coverage result to codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
